import Header from '@/ui/Header';
import Footer from '@/ui/Footer';
import Background from '@/ui/Background';

import type { Metadata } from "next";
import { Sen } from "next/font/google";
import "./globals.css";
import { getSession } from '@/lib/auth';

const font = Sen({ weight: "700", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body className={font.className}>
        <Header session={session}/>
        <Background>
          {children}
        </Background>
        <Footer />
      </body>
    </html>
  );
}
